project:
  type: website

website:
  title: "Sam Hillman"
  site-url: https://www.samhillman.com
  description: "Sam Hillman's personal webpage"
  navbar:
    right:
      - text: Contact
        href: contact.qmd
      - text: Blog
        href: blog.qmd 
      - text: CV
        href: https://www.samhillmancv.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/samghillman/
      - icon: github
        href: https://github.com/SamHillman
      - icon: twitter
        href: https://twitter.com/SamHillman

format:
  html:
    theme: theme.scss

editor: 
  mode: source

