project:
  type: website

website:
  title: "Sam Hillman"
  site-url: https://www.samhillman.com
  description: "Sam Hillman's personal webpage"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/SamHillman
      - icon: twitter
        href: https://twitter.com/SamHillman
      - text: "{{< ai google-scholar >}}"      
        href: https://scholar.google.co.uk/citations?user=kKydRfAAAAAJ&hl=en
   

format:
  html:
    theme: theme.scss

editor: 
  mode: source

